### ISSUE TITLE
Connecting to peers

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#13]
Should work automatically

**Comment by maxirmx** [comment]
It is a matter of having at least one node running all the time. To achieve it we need to have several "seed" nodes preferrably available by URLs, not by ip addresses.  
The URLs of these nodes are either hardcoded into all clients or placed into a config file that is distributed with all clients.

**Comment by MarkH24** [comment]
so if I create 5 seed nodes with an url and run them this will be sufficient. Can also any of these be a miner mining all the time?

**Comment by maxirmx** [comment]
You need to create nodes that have urls or at least fixed IPs.
If there is any kind of address that it permanent, it can be hardcoded and used as entry point to the netwoerk.
Right now I have single AWS instance that does not have neither fixed IP, nor URL.

**Comment by maxirmx** [comment]
As for miner, dogecoin reference implementation does not contain 'background miner' that is supposed to run all the time.
Such miner used to be in the code several years ago but it is not a part of last versions. I think everyone uses specialized applications for mining.

I think it is because these days specialized hardware is used for mining and there is no value in mainating useless functions.

If you want me to develop "some" miner it is possible, but I need better understanding of your expectations(#4). At list wheather you want it to be standalone, integrated into backbone node, integrated into GUI or something else.

**Comment by maxirmx** [comment]
See also #15

**Comment by maxirmx** [comment]
Closed by
https://github.com/coin-green/CoinGreen/releases/tag/v2.0.0.3
