### ISSUE TITLE
Create a network

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#15]
If I am right about the idea of the network, then miners need to be running on a server and there is a kind of mechanism for consensus among them so they need to be able to find each others - this is per my understanding the key idea of a blockchain.

So how can we proceed here  as this Is the key objective...

**Comment by maxirmx** [comment]
There is no mechanism for consensus related to connections. 

Connection between nodes is set up using either:
1) Hardcoded URLs of seed nodes   [I am not running any seed nodes]
2) Using configuration file commands connect or addnode
Sample:
https://github.com/coin-green/CoinGreen/blob/master/contrib/debian/examples/coingreen.conf

```
##############################################################
##            Quick Primer on addnode vs connect            
##  Let's say for instance you use addnode=4.2.2.4          
##  addnode will connect you to and tell you about the      
##    nodes connected to 4.2.2.4.  In addition it will tell 
##    the other nodes connected to it that you exist so     
##    they can connect to you.                              
##  connect will not do the above when you 'connect' to it. 
##    It will *only* connect you to 4.2.2.4 and no one else.
##                                                          
##  So if you're behind a firewall, or have other problems  
##  finding nodes, add some using 'addnode'.                
##                                                          
##  If you want to stay private, use 'connect' to only      
##  connect to "trusted" nodes.                             
##                                                          
##  If you run multiple nodes on a LAN, there's no need for 
##  all of them to open lots of connections.  Instead       
##  'connect' them all to one node that is port forwarded   
##  and has lots of connections.                            
##       Thanks goes to [Noodle] on Freenode.               
##############################################################
```

Now I do not have neither domain, nor even fixed IP.  Just a single node running at AWS with potentially varying IP.
So when you start client application you have to manually configure connection to whatever IP  was assigned at the last start

**Comment by maxirmx** [comment]
As for miner, dogecoin reference implementation does not contain 'background miner'  that is supposed to run all the time.
Such miner used to be in the code several years ago but it is not a part of last versions.  I think everyone uses specialized applications for mining.

I think it is because these days specialized hardware is used for mining and there is no value in maintaing useless functions.

If you want me to develop "some" miner  it is possible, but I need better understanding of your expectations(https://github.com/coin-green/genesis/issues/4).  At the bare minimum, wheather you want the miner to be standalone, integrated into backbone node, integrated into GUI or something else.

**Comment by maxirmx** [comment]
I think #25 closes this problem
