### ISSUE TITLE
Transaction fees

### ISSUE THREAD

**Issue by MarkH24** [coin-green/genesis#24]
How much is the transaction fee currently for one transfer?
How can we set that?
Will that change over time? (As in Bitcoin and Dogecoin it seems it is flactuating)

**Comment by maxirmx** [comment]
Transaction fees were inherited from dogecoin without any alterations.
As far as I understand there  is minmal fee - 1 CoinGreen per kilobyte. You may see it as 1 CG per transaction.
The sender can pay extra. Transactions with higher fees are verified with higher priority.
The sender can set fee at 'Send Dialog'.

**Comment by MarkH24** [comment]
that could be adjusted to lower fees, e.g. 0.1 CG per kilobyte?
how much data has a typical transaction where I send some coins from me to you?

**Comment by maxirmx** [comment]
In dogecoin minimal value is 1 DOGE.  Everything smaller is considered 'dust' and ignored.  This feature was inhereted by CG.

So to reduce transaction fee below 1 CG different 'dust' threshold shall be established.
After that the minimal transaction cost can be set to any value equal or above 'dust' threshold.

It does not look like a hard task unless I am missing some hidden complexity.


If you send some coins it will be below 1000 bytes.   It is rounded up to 1K.    
I am not able to understand per Kb concept so far since all transaction are like this.

**Comment by MarkH24** [comment]
I guess my question was kind of influenced by Ethereum as you can write there also smart contracts which can differ noteworthy in complexity and hence space in a block.

However, in terms of the amount. Somthing which would be very smart: Instead of defining a fixed amount per transfer, my prefered solution would be a fee to be a percentage of each transaction, e.g. 0.1% of the amount or even less.

**Comment by maxirmx** [comment]
There is minimal fee that can be set to any value you want providing that it is higher then dust.
Imagine that you define dust as anything below 0,05 CG and minimal fee as 0.1% of transaction.   What should be the minimal fee for 1CG transfer ? I assume it will be 0.05 CG

So you have to specify both - dust threshold and transaction fee rule

**Comment by MarkH24** [comment]
in principle I would define dust as anything below 0.001 CG
and then set TX fees to 0.1% - that would be rather smart

**Comment by maxirmx** [comment]
Regarding TX fee - 0,1%    
Would you  like it to be:
1) minimal possible fee that can be increased by the user (for example,  if he/she wishes to pay for high priority confirmation)
or
2) recommended fee that will be preset in GUI but can be reduced or increased  by the user 
or
3) the preset fee that cannot be adjusted in the GUI
or
4) the only possible fee that cannot be changed at all and thus becomes a part of the consensus  (transactins with other fee will be rejected)

**Comment by MarkH24** [comment]
1 - but also depends on the complexity of implementation 
Else it would be 3 I guess

**Comment by MarkH24** [comment]
Is that currently implement? 
I am woundering because I get now the 23 coins to my wallet from the blocks - so seems currently nothing is deducted?

**Comment by maxirmx** [comment]
When a new block is created it has fixed size and thus can include only limited number of transactions. From miner's point of view transfer amount does not matter but the size required to include it to the ledger matters.


That's why relay fee in Dogecoin is calculated per kilobyte and miner applications select transactions with highest per kilobyte rate. As far as I understand Bitcoin calculates fees per byte but applies similar principles.


When you ask to set rransaction relay fee as %% of amount, not size it works against miner's interest but towards payers. I will leave it up to you wheather it is feasible or not.

**Comment by maxirmx** [comment]
**Development status:**
_Frozen at branch 2.0.0.4_

Nevertheless, I have a client version that sets relay fee as 0.1% of transaction amount. The issue I am facing is the network that still converts it to per kilobyte fee and discard sone transactions thinking that the rate is too low.  I believe I need one more week to remove this control.

**Comment by maxirmx** [comment]
We will set 0.001 per kb min and 0.1 per kb max
_**Branch 2.0.0.5**_
